apiVersion: elasticache.aws.upbound.io/v1beta2
kind: ReplicationGroup
metadata:
  annotations:
    meta.upbound.io/example-id: elasticache/v1beta2/replicationgroup
  labels:
    testing.upbound.io/example-name: example
  name: example-random
spec:
  forProvider:
    automaticFailoverEnabled: true
    description: example description
    engineVersion: "7.1"
    nodeType: cache.m4.large
    numCacheClusters: 2
    parameterGroupName: default.redis7
    port: 6379
    region: eu-west-1
    subnetGroupName: default
